travis:
  secure:
    BINSTAR_TOKEN: m/l9CcgA6ldzBripxHIORbthM40WtjaEMHvVweGSJTyvAcZZJla3KPgdRJVh9I9Ck8nczJ6kxWjJIIaQMc23OLZ9tdoBpcO3V1lUC42ZHX8oWLMtZdp70BdkdfnIq8ulBtyxuSyu0rnfWv0VVLcMAezCHNGR1muJu43PB0J1txhagAUhWvxrZPnWeYrekGcCMC/iU1Ho7Tc3fE4lbq3MQmUPOFrX5kkGqQ1X38uZ3gCSRaPgU8bBXq8JfVAtS38niOSV2RpTuY4ymPTo/BC/xQbsh2qE2x0kIbcOhTG1Rya/2ljNgK5JuvgfUXp4jShC+lFbvXA0TCVLeYCbKKNuvWfZrxzSW2TauU4Ud5uqMzYCYy4iXH4Xp09duQ8pW3XRURB1Bg9t0K5vI1RywCfaPsnYOJuwa2CCLmarxo3YQFTLDF2V/EuIRIhzkbrIKQpv9nMIOKAJNrqhEv/TrXxyYw9I0CUI0c4sOvZhU+yidXaI9B9yGEDjZC3oY3nJJ7SrZvBos1omgjJsprUCXyBwveLdUYtds4uM7IX/eJtciCFCfLd+2QIqJiaw6hEi/Y/eUmrmL5HC6fknIxdWqdP0P5Kdx6ySIYeTK7e4Y5gzr+mPSzBHFb2YJUan9iZvmau7LNs5XJRv59qHqN1TBrg11WK38Ly1KPbKOMYDA7cKZ2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
